name: Notifications

on:
  release:
    types: [published]

jobs:
  github-release-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.15.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "GitHub Releases"
          avatar_url: "https://cdn.discordapp.com/avatars/972247312782987334/139d847c8df1ad7b14f04b68fa382646.webp?size=80"
          footer_title: "Changelog"
          footer_timestamp: true
          footer_icon_url: "https://cdn.discordapp.com/avatars/972247312782987334/139d847c8df1ad7b14f04b68fa382646.webp?size=80"